fish: Fix build error if built without readline.
fish.c:1447: error: 'add_history_line' defined but not used [-Wunused-function]

(Reported by Matt Booth)

(cherry picked from commit 5af010c96d687a7cf5251107a74770a231f42b77)