lib/create.c: Fix string passed to printf-like function
  create.c: In function 'disk_create_qcow2':
  create.c:372:5: error: format not a string literal and no format arguments [-Werror=format-security]
    372 |     debug (g, cmd_stdout);
        |     ^~~~~

Fixes: commit 606aa1d1822260905a5dd8a47f29a66652168f22