lib/launch-libvirt.c: Fix type of outlen parameter of base64_decode_alloc_ctx
In file included from launch-libvirt.c:49:
launch-libvirt.c: In function 'add_secret':
launch-libvirt.c:1956:54: error: pointer targets in passing argument 5 of 'base64_decode_alloc_ctx' differ in signedness [-Werror=pointer-sign]
 1956 |                               (char **) &secret_raw, &secret_raw_len)) {
      |                                                      ^~~~~~~~~~~~~~~
      |                                                      |
      |                                                      size_t * {aka long unsigned int *}
../gnulib/lib/base64.h:62:56: note: in definition of macro 'base64_decode_alloc'
   62 |         base64_decode_alloc_ctx (NULL, in, inlen, out, outlen)
      |                                                        ^~~~~~
../gnulib/lib/base64.h:56:57: note: expected 'idx_t *' {aka 'long int *'} but argument is of type 'size_t *' {aka 'long unsigned int *'}
   56 |                                      char **out, idx_t *outlen);
      |                                                  ~~~~~~~^~~~~~
cc1: all warnings being treated as errors

Note this patch is only required in the stable branch because
of the gnulib update.