daemon: Disable -Wstack-usage warning
When using LTO, inlining something (I'm unclear what exactly) causes
these errors:

stubs-1.c: In function 'md_create_stub':
stubs-1.c:1929:1: error: stack usage might be unbounded [-Werror=stack-usage=]
 1929 | md_create_stub (XDR *xdr_in)
      | ^
stubs-0.c: In function 'mkfs_btrfs_stub':
stubs-0.c:1984:1: error: stack usage might be unbounded [-Werror=stack-usage=]
 1984 | mkfs_btrfs_stub (XDR *xdr_in)
      | ^
stubs-3.c: In function 'btrfs_device_delete_stub':
stubs-3.c:477:1: error: stack usage might be unbounded [-Werror=stack-usage=]
  477 | btrfs_device_delete_stub (XDR *xdr_in)
      | ^
stubs-3.c: In function 'btrfs_image_stub':
stubs-3.c:694:1: error: stack usage might be unbounded [-Werror=stack-usage=]
  694 | btrfs_image_stub (XDR *xdr_in)
      | ^
stubs-5.c: In function 'btrfs_device_add_stub':
stubs-5.c:247:1: error: stack usage might be unbounded [-Werror=stack-usage=]
  247 | btrfs_device_add_stub (XDR *xdr_in)
      | ^

Note this is only for the stable branch.