mlxml: Fix pointed target signedness.
xml-c.c: In function 'mllib_xml_to_string':
xml-c.c:199:47: error: pointer targets in passing argument 2 of 'caml_alloc_initialized_string' differ in signedness [-Werror=pointer-sign]
  199 |   strv = caml_alloc_initialized_string (size, mem);
      |                                               ^~~
      |                                               |
      |                                               xmlChar * {aka unsigned char *}

(cherry picked from commit ea10827b4cfb3cfe5f782421c01d2902e5f73f90)