v2v: Help RHEL 6 OCaml to determine type of class.
File input_libvirt_other.ml, line 1, characters 0-1:
Error: The implementation input_libvirt_other.ml
       does not match the interface input_libvirt_other.cmi:
       Class declarations do not match:
         class virtual input_libvirt :
           'a ->
           string option ->
           string ->
           object
             method adjust_overlay_parameters : Types.overlay -> unit
             method as_options : string
             method virtual source : unit -> Types.source
           end
       does not match
         class virtual input_libvirt :
           string option ->
           string option ->
           string ->
           object
             method adjust_overlay_parameters : Types.overlay -> unit
             method as_options : string
             method virtual source : unit -> Types.source
           end
       A parameter has type 'a but is expected to have type string option

(cherry picked from commit 00bceec4216da7757acf0aa7174a99fb0b6deeb5)