daemon/xfs.c: Ignore bogus warnings from -fanalyzer
Lots of variations of this.  It cannot happen because we check that
section != NULL just before calling this code.

                'parse_xfs_info': event 41
                  |
                  |../lib/guestfs-internal-all.h:50:21:
                  |   50 | #define STREQ(a,b) (strcmp((a),(b)) == 0)
                  |      |                     ^~~~~~~~~~~~~~~
                  |      |                     |
                  |      |                     (41) argument 1 ('section') from (35) could be NULL where non-null expected
xfs.c:186:13: note: in expansion of macro 'STREQ'
                  |  186 |         if (STREQ (section, "meta-data")) {
                  |      |             ^~~~~
                  |

Similarly this error does not appear possible:

xfs.c:154:7: error: double-'free' of 'ret_9' [CWE-415] [-Werror=analyzer-double-free]
  154 |       free (section);
      |       ^

See comment for why these suppressions are placed centrally.