builder: Fix comparison between signed/unsigned in parallel xzcat.
block.header_size is uint32_t so cannot be compared directly with n (ssize_t).

pxzcat-c.c: In function 'worker_thread':
pxzcat-c.c:602:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (n >= 0 && n != block.header_size-1) {
                     ^

(cherry picked from commit 3053785db82c3aaf935c582146fd863d3618910f)