v2v: -o rhv-upload: Fix request headers in pread
headers was initialized with a set literal {"key", "value"} instead of
dict literal {"key": "value"}.

Calling pread() will fail with:

    AttributeError: 'set' object has no attribute 'items'

I did not test the changed code, but it was not tested before, so it is
unlikely to be worse.

Detected by pylint.