v2v: -o rhv-upload: Fix emulated zero
Replace python 2 only "buffer" with "memoryview".

Falling back to emulated zero would fail with:

    NameError: name 'buffer' is not defined

I did not test the changed code but it was not tested before so it is
unlikely to be worse.

Detected by pylint.