journal: Fix incorrect printf format specifier for 32-bit.
journal.c: In function 'do_journal_skip':
journal.c:134:5: error: format '%zd' expects argument of type 'signed size_t', but argument 3 has type 'int64_t' [-Werror=format=]
     reply_with_perror_errno (-r, "failed to skip %zd journal entries", skip);
     ^

This fixes commit 5cb7f294f6a5a8b4a68e940c30ca9af0fe0741d5.