v2v: -o libvirt: Don't write only <vendor> without <model> (RHBZ#1591789).
Avoids the libvirt error:

  error: XML error: CPU vendor specified without CPU model

(cherry picked from commit e2910eeaf84afe63887afdc62b319bff1549d296)